### ISSUE TITLE
Logo Proposal for Instapack

### ISSUE THREAD

**Issue by area55git** [ryanelian/instapack#229]
Hi @ryanelian, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Instapack.

I will be pleased to collaborate with you.

**Comment by ryanelian** [comment]
Hi @area55git 

Sure, I'm open for collaborations. Open Source is about these stuffs anyway, the more the merrier. 👍 

I myself envisioned instapack logo to be:
- Futuristic.
- Made of glass or metal. Or both.
- With a gradient touch of [TypeScript blue color](https://github.com/remojansen/logo.ts) + [W3C HTML5 logo orange color](https://www.w3.org/html/logo/) turning to [JS yellow color](https://commons.wikimedia.org/wiki/File:JavaScript-logo.png) (signifying compilation)
- and a touch of [Sass magenta color](https://sass-lang.com/styleguide/brand) somewhere (or not)
- Speaking of gradients, I personally loooove how [Visual Studio 2010 logo](https://user-images.githubusercontent.com/8892187/44415034-897c3c80-a599-11e8-9734-f8e894dc9f85.png) looks like. (Beautiful gradients, excellent use of transparency, not too simple)

But yah, those are just random ramblings of mine. I'm not a professional logo designer. 😄 

What do you have in mind?

**Comment by area55git** [comment]
@ryanelian For me, it is a pleasure to be able to make a contribution in Instapack, I will review and study your suggestions to start with the sketches, in a couple of days I will send you.

**Comment by area55git** [comment]
Hi Ryan, I have 2 proposals to show you

![logo proposal for instapack](https://user-images.githubusercontent.com/38330420/44547615-ba6b8700-a6e9-11e8-8c92-27c08a3527e7.jpg)

In the first proposal, I used the project initials ( i + p) in the form of an outline with a degraded color from orange to yellow.

In the second proposal, I combined an arrow representing a compilation with the letter "i" of the name. Using the Sass color reference combined with green to give contrast.

I hope you like some.

**Comment by area55git** [comment]
Other color options:

![logo proposal for instapack](https://user-images.githubusercontent.com/38330420/44548378-e8ea6180-a6eb-11e8-9a4b-f65a9b96b136.jpg)

**Comment by ryanelian** [comment]
![image](https://user-images.githubusercontent.com/8892187/44565534-d119e880-a792-11e8-966a-85cd1435afc5.png)

Very interesting. It reminds me of [Pied Piper](https://user-images.githubusercontent.com/8892187/44565056-59e35500-a790-11e8-9854-bd62c22e3b9b.png) logo with [Tron Legacy](https://user-images.githubusercontent.com/8892187/44565072-6bc4f800-a790-11e8-8b23-b7e5be66b50d.png)-ish feel.

I personally don't like the other logo, so let's work from this one.

----

Guys, please vote which logo is better: https://www.strawpoll.me/16326027

I also made a (very shitty) 5 minutes paint job using above logo with gradient from TypeScript blue to JS yellow for visualization:

![image](https://user-images.githubusercontent.com/8892187/44565649-7208a380-a793-11e8-97ff-f996616dd07b.png)

Please also vote if this is actually a good idea: https://www.strawpoll.me/16326033

**Comment by sammyarno** [comment]
hey @ryanelian  I think would be better if the gradient flows from left to right, not diagonally

also I love this @area55git design
![image](https://user-images.githubusercontent.com/28641692/44566069-af6e3080-a795-11e8-9af0-4b721d96070d.png)

**Comment by ryanelian** [comment]
![image](https://user-images.githubusercontent.com/8892187/44571684-ac7e3a80-a7ab-11e8-900d-d77127af0c2e.png)

Developed an alternative color which involves the four language elements:
- TypeScript blue `#007ACC` gradient from bottom left to top right, turning JavaScript yellow `#f3df49`
- Sass magenta `#cc6699` gradient, opaque from top left to middle, turning HTML5 orange `#E34C26` with alpha zero (fully transparent)

**Comment by ryanelian** [comment]
![instapack4](https://user-images.githubusercontent.com/8892187/44572516-3929f800-a7ae-11e8-9a75-6414ce47475e.png)

The outline version of the logo, with same gradient color scheme.

**Comment by ryanelian** [comment]
Title fontographies:

![image](https://user-images.githubusercontent.com/8892187/44601563-1546d080-a807-11e8-80e7-e82f1b98177b.png)

![image](https://user-images.githubusercontent.com/8892187/44601582-25f74680-a807-11e8-9358-61ea5583831a.png)

![image](https://user-images.githubusercontent.com/8892187/44601605-31e30880-a807-11e8-9bcb-471d92e4fe64.png)

![image](https://user-images.githubusercontent.com/8892187/44601624-445d4200-a807-11e8-9685-84ccb4008770.png)

![image](https://user-images.githubusercontent.com/8892187/44601633-4de6aa00-a807-11e8-8e96-c59a6b36f9e8.png)

![image](https://user-images.githubusercontent.com/8892187/44601646-5808a880-a807-11e8-9534-676b624d2cab.png)

![image](https://user-images.githubusercontent.com/8892187/44601789-d1080000-a807-11e8-9bfa-269850e47f74.png)

**Comment by Tieantono** [comment]
> Title fontographies:

Between Comfortaa and Audiowide.

**Comment by area55git** [comment]
![logo proposal for instapack](https://user-images.githubusercontent.com/38330420/44604917-76de4f00-a7b5-11e8-83eb-744e97bf00a3.jpg)

I used the font called Segoe UI because it has the dot of the letter "i" rounded and its corners are rounded, it goes very well with the logo.

**Comment by area55git** [comment]
Do you want to see it with one of the sources suggested by you?

**Comment by area55git** [comment]
I think we could square an hour to be connected at the same time, now in my country, it's 4:00 p.m. I don't know how many hours apart there are from your country.

**Comment by ryanelian** [comment]
![image](https://user-images.githubusercontent.com/8892187/44641170-daec5780-a9ef-11e8-89f3-816f26edefa9.png)

Dope. We like that one.

> Do you want to see it with one of the sources suggested by you?

Try [Comfortaa](https://fonts.google.com/specimen/Comfortaa)

**Comment by area55git** [comment]
Hi Ryan, I'm sending you a sample with the suggested font, a vertical and horizontal version, a delineated version and a dark background version, I hope you like them.

![logo proposal for instapack](https://user-images.githubusercontent.com/38330420/44665799-cf476380-a9e4-11e8-9cd9-51ba14cfe91c.jpg)

**Comment by ryanelian** [comment]
![image](https://user-images.githubusercontent.com/8892187/44700093-92956e00-aab1-11e8-9320-c59ef2b3f576.png)

This one is okay. The font is not too thicc that it overpowers the logo.

It would be nice if I can release 6.7.0 (which ships hot reload feature), with this logo.

![image](https://user-images.githubusercontent.com/8892187/44700159-046db780-aab2-11e8-823d-7591195a750a.png)

Interesting. Although not practical as the official emblem (since the logo needs to be put on the system notification icon) and more like a banner, that looks surprisingly good.

**Comment by area55git** [comment]
Hi @ryanelian during the course of the day I'll send you the files.

**Comment by area55git** [comment]
Hi, I apologize for the delay, I live in Venezuela and lately we have had many problems with the internet, more than a week without signal. Soon I will send the final files, again I apologize for the delay.

**Comment by ryanelian** [comment]
Next month I will be releasing the new instapack 7. It would be really nice if I can incorporate the logo into the finished product. 😃

**Comment by area55git** [comment]
Hello, @ryanelian, I want to apologize for the long absence, I tell you that I'm Venezuelan, there the political situation became very tense and this affected my economic position, for that reason I decided to leave my country to seek improvements in my life, now I'm in another South American country called Ecuador, for the above exposed I ask you if you still need the final files of the logo so you can fulfill my collaboration, if you have some corrections please you can notify them.

**Comment by ryanelian** [comment]
Closed due to non-activity.
