### ISSUE TITLE
Bug Output Display

### ISSUE THREAD

**Issue by mikhael95** [ryanelian/instapack#32]
![screenshot 217](https://user-images.githubusercontent.com/19304772/33588520-dc066cd4-d9a5-11e7-9583-59ed54a818b7.png)

**Comment by ryanelian** [comment]
Hello Mikhael, tell me more about your environment (because instapack is complaining about Node.js version):

1. What version of Node.js do you use? `node -v`

> instapack 5 is supported on the latest Node.js 8 LTS

2. What did you use to install instapack?

3. Have you tried updating to instapack 5.1.1 and see whether the problem disappears?

**Comment by mikhael95** [comment]
Okay it was solved after I tried updating it to Instapack 5.1.1. Thank you
