### ISSUE TITLE
Specify source folder instead of automatically using js/ ?

### ISSUE THREAD

**Issue by creepinson** [ryanelian/instapack#933]
Right now I"m getting this:
```
[17:54:29] Entry file /mnt/c/Users/thebo/Documents/Code/game-engine/test/js/index.ts was not found. Aborting JS build!

```

However, I have my typescript source code in src/ and not js/.

I also get a similar error after this
```
ERROR during JS build:

undefined (main)
 ModuleNotFoundError: Module not found: Error: Can't resolve '/mnt/c/Users/thebo/Documents/Code/game-engine/test/js/index.ts' in '/mnt/c/Users/thebo/Documents/Code/game-engine'
    at /mnt/c/Users/thebo/Documents/Code/game-engine/node_modules/.pnpm/webpack@5.6.0/node_modules/webpack/lib/Compilation.js:1479:28
```

I don't see any option to specify the source folder. I already have the following instapack config as well:
```json
{
    "instapack": {
        "input": "test",
        "output": "test/dist",
        "jsOut": "bundle.js"
    }
}
```

**Comment by ryanelian** [comment]
This feature is not available at the moment.

The JS folder is deliberately set to be `[input]/js` and the CSS folder to `[input]/css`

Are there any specific reason why you can't just put your entry point to `[input]/js/index.ts` rather than `test/src/index.ts`?
